language: php

php:
  - 5.6

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  
notifications:
  email:
    - jhon.jairo.alvarez.londono@gmail.com
