language: php

php:
  - 5.6

env:
  - SYMFONY_VERSION=3.4.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

notifications:
  email:
    - jhon.jairo.alvarez.londono@gmail.com
